### ISSUE TITLE
[Question Creator] Reporting section of a question results in change to completely different question

### ISSUE THREAD

**Issue by TrainFanatic** [donnutdev/StudyHaven#1]
**Steps to recreate:**

1. Under question creator, select Physics + Physical Quantities and Units (any other combo should work)
2. Select any section of question. 
3. Click report

This differs from the intended behaviour of fixing the selected portion.

**Comment by donnutdev** [comment]
Issue fixed, regenerating questions will now actually fix the previous question and return it.
